### ISSUE TITLE
Deployment of access levels and service control perimeter should be optional and "allowed services" parameterizable

### ISSUE THREAD

**Issue by mromascanu123** [terraform-google-modules/terraform-example-foundation#1185] opened 2024-04-10 17:08 UTC
### TL;DR

In module 3-networks-hub-and-spoke/modules/restricted_shared_vpc (and the same in 3-networks-dual-svpc/modules/restricted_shared_vpc) there is no option to conditionally enable the deployment of SCP and access levels.
Moreover: why hardcode vpc_accessible_services = ["RESTRICTED-SERVICES"]. Shouldn't be configurable? Default is "*"

### Terraform Resources

```markdown
https://registry.terraform.io/modules/terraform-google-modules/vpc-service-controls/google/latest/submodules/regular_service_perimeter?tab=inputs
```

### Detailed design

```markdown
Add an enablement variable
```

**Comment by eeaton** [comment] 2024-05-20 16:45
I'll close this Issue as a duplicate of https://github.com/terraform-google-modules/terraform-example-foundation/issues/1209, I'm tracking work to enable VPCSC in dryrun mode and avoid the friction associated with immediately deploying an enforced VPCSC perimeter. 

However to the specific question:
>why hardcode vpc_accessible_services = ["RESTRICTED-SERVICES"]. Shouldn't be configurable? Default is "*"

This is a confusingly named convention for vpc_accessible_services, but it's working as intended.
"restricted services"  means API traffic for this service cannot cross the perimeter.
"VPC accessible services" means that API endpoints can be reached from a VPC inside the perimeter.
`vpc_accessible_services = ["RESTRICTED-SERVICES"]` is the [recommended convention](https://cloud.google.com/vpc-service-controls/docs/enable#:~:text=disallow%20access%20to%20unsupported%20services) to ensure these two settings align. The string "RESTRICTED-SERVICES" is equivalent to listing out all the services already configured for this perimeter as restricted. So only the endpoints for Google APIs can be reached from the VPC if they are restricted in the perimeter.

This helps avoid edge cases such as:

- Google Cloud APIs that are not compatible with VPCSC might be accessed from the customer VPC inside the perimeter, leading to exfiltration
- New services that are created in the future with VPCSC support that are not explicitly restricted in the customer perimeter as restricted might suddenly create an exfiltration path tomorrow where there was none today

**Closed by eeaton** 2024-05-20 16:45 UTC
Labels: enhancement
