### ISSUE TITLE
Add a README with instructions on how to configure terraform-validator

### ISSUE THREAD

**Issue by daniel-cit** [terraform-google-modules/terraform-example-foundation#120] opened 2020-07-26 03:23 UTC
(`develop` branch)
Add a separated README file with instructions on how to configure terraform-validator in the cloud build/jenkins context.

- The service account running the build (cloud build service account if using cloud build) need at least these roles at the parent folder:
  - Browser
  - Security Reviewer
- add a link to [how to install the policies repo](https://github.com/forseti-security/policy-library/blob/master/docs/user_guide.md#how-to-use-terraform-validator)
- explanation for configuration of the `_POLICY_REPO` variable in the cloud build trigger
  - value should be `/workspace/RELATIVE-PATH-TO-POLICY-FOLDER-INSIDE-REPO`

**Comment by rjerrems** [comment] 2020-08-06 00:04
Closing as it is a duplicate of https://github.com/terraform-google-modules/terraform-example-foundation/issues/153

**Closed by rjerrems** 2020-08-06 00:04 UTC
Labels: documentation
